name: Hello
on: push
jobs:
    hello:  # job id
        runs-on: ubuntu-latest  # runner
        steps:
            - run: echo "Hello, World!" # shell command
            - uses: actions/checkout@v4 # action (module)
